version: '3'
services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: WordPress
  wpos:
    image: wordpress:5.1.1-php7.3-apache
    volumes:
      - wp_storage:/var/www/html
    restart: always
    ports:
      - 8085:80
    depends_on:
      - dbos
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: WordPress

volumes:
  wp_storage:
  mysql_storage:
