FROM centos

RUN yum install curl-7.61.1-8.el8.x86_64

RUN yum install net-tools-2.0-0.51.20160912git.el8.x86_64

RUN yum install vim-enhanced-8.0.1763-10.el8.x86_64

CMD echo "hi this is a container"

